#!/bin/sh

cat << EOF
################################################################################
# uconsole-sdk-version
################################################################################
UCONSOLE_SDK_VERSION="$(dpkg-query -W -f='${Version}\n' uconsole-sdk)"
$( [ -f /opt/uconsole-sdk/sdk-info ] &&
  cat /opt/uconsole-sdk/sdk-info
)
################################################################################
EOF
