#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	# Create any missing keys
	if [ ! -e /data/config/ssh/ssh_host_ecdsa_key ]; then
		echo "Generating host ECDSA key..."
		/usr/bin/ssh-keygen -q -f /data/config/ssh/ssh_host_ecdsa_key -N '' -t ecdsa -b 521
	fi

	if [ ! -e /data/config/ssh/ssh_host_ed25519_key ]; then
		echo "Generating host ED25519 key..."
		/usr/bin/ssh-keygen -q -f /data/config/ssh/ssh_host_ed25519_key -N '' -t ed25519
	fi
	
	if [ ! -e /data/config/ssh/ssh_host_rsa_key ]; then
		echo "Generating host RSA key..."
		/usr/bin/ssh-keygen -q -f /data/config/ssh/ssh_host_rsa_key -N '' -t rsa
	fi

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

